### ISSUE TITLE
'hod list' fails hard on unexpected file in $HOME/.config/hod.d

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#192]
User was faced with:

```
Traceback (most recent call last):
 File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "build/bdist.linux-x86_64/egg/hod/main.py", line 92, in <module>
 File "build/bdist.linux-x86_64/egg/hod/main.py", line 80, in main
 File "build/bdist.linux-x86_64/egg/hod/subcommands/listcmd.py", line 90, in run
 File "/usr/lib/python2.7/site-packages/vsc/utils/fancylogger.py", line 322, in raiseException
   message += " (%s)" % detail
TypeError: unsupported operand type(s) for +=: 'exceptions.UnboundLocalError' and 'str'
```

Actual problem was hidden due to unresolved bug in #191:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/hod/main.py", line 92, in <module>
  File "build/bdist.linux-x86_64/egg/hod/main.py", line 80, in main
  File "build/bdist.linux-x86_64/egg/hod/subcommands/listcmd.py", line 90, in run
  File "build/bdist.linux-x86_64/egg/hod/subcommands/listcmd.py", line 79, in run
  File "build/bdist.linux-x86_64/egg/hod/cluster.py", line 197, in mk_cluster_info_dict
UnboundLocalError: local variable 'jobid' referenced before assignment (local variable 'jobid' referenced before assignment)
```

This was caused by a *file* that was manually created in `$HOME/.config/hod.d` by the user, which was handled quite badly in the existing codebase.

To fix this, we need to:

i) make sure that `jobid` is always defined in `mk_cluster_info_dict` (i.e. also in the `except`)
ii) only consider *directories*, not files in `.config/hod.d`
iii) maybe also implement some kind of sanity check for `.config/hod.d` to report unexpected files

**Comment by boegel** [comment]
fixed in #193
