### ISSUE TITLE
'hod dists' is broken if HOD is installed with EasyBuild

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#78]
```
$ hod dists
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-minimal/lib/hod/main.py", line 88, in <module>
    sys.exit(main(sys.argv))
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-minimal/lib/hod/main.py", line 76, in main
    return subcmd.run(args)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-minimal/lib/hod/subcommands/dists.py", line 45, in run
    print '\n'.join(avail_dists())
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-minimal/lib/hod/config/config.py", line 483, in avail_dists
    return resource_listdir(pkg, HOD_ETC_DIR)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/setuptools/1.4.2/lib/pkg_resources.py", line 902, in resource_listdir
    resource_name
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/setuptools/1.4.2/lib/pkg_resources.py", line 1334, in resource_listdir
    return self._listdir(self._fn(self.module_path,resource_name))
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/setuptools/1.4.2/lib/pkg_resources.py", line 1420, in _listdir
    return os.listdir(path)
OSError: [Errno 2] No such file or directory: '/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-minimal/lib/etc/hod'
```

**Comment by boegel** [comment]
```
$ ls $EBROOTHANYTHINGONDEMAND
bin  easybuild	etc  lib
$ ls $EBROOTHANYTHINGONDEMAND/etc/hod
Hadoop-2.3.0-cdh5.0.0  Hadoop-2.5.0-cdh5.3.1-gpfs  Hadoop-2.5.0-cdh5.3.1-native  Hadoop-on-lustre2  IPython-notebook-3.2.1
```

**Comment by boegel** [comment]
this patch fixes the problem:

```diff
--- lib/hod/config/config.py.orig	2015-09-14 21:44:04.978644000 +0200
+++ /lib/hod/config/config.py	2015-09-14 21:46:01.137706635 +0200
@@ -32,7 +32,6 @@
 from collections import Mapping, namedtuple
 from copy import deepcopy
 from os.path import join as mkpath, dirname, realpath
-from pkg_resources import Requirement, resource_filename, resource_listdir
 
 import hod
 from hod.node.node import Node
@@ -463,8 +462,7 @@
 
 def resolve_dists_dir():
     """Resolve path to distributions."""
-    pkg = Requirement.parse(hod.NAME)
-    return resource_filename(pkg, HOD_ETC_DIR)
+    return os.path.join(os.getenv('EBROOTHANYTHINGONDEMAND'), HOD_ETC_DIR)
 
 
 def resolve_dist_path(dist):
@@ -479,8 +477,7 @@
 
 def avail_dists():
     """Return a list of available distributions"""
-    pkg = Requirement.parse(hod.NAME)
-    return resource_listdir(pkg, HOD_ETC_DIR)
+    return os.listdir(resolve_dists_dir())
 
 
 def resolve_config_paths(config, dist):
```

**Comment by boegel** [comment]
Of course, the patch is only a workaround, I don't think relying on `$EBROOTHANYTHINGONDEMAND` is a good idea, but it does work.

**Comment by boegel** [comment]
@ehiggs: basically, this tells me we need a fallback mechanism for the use of `Requirement`, but I'm not happy with relying on `$EBROOTHANYTHINGONDEMAND` since that implies that HOD was installed via EB...

thougths?

**Comment by ehiggs** [comment]
I've been using EasyBuild the whole time to make my hod install on our clusters, so I'm not sure this is actually an issue. It looks like the problem is using `VersionDependentPythonPackage` which we discovered was not usable as an egg install.

```python
easyblock = 'PythonPackage'

name = 'hanythingondemand'
version = '3.0.0dev'

homepage = 'https://github.com/hpcugent/hanythingondemand'
description = """HanythingOnDemand (HOD) is a system for provisioning virtual Hadoop clusters over a large physical cluster.
It uses the Torque resource manager to do node allocation."""

toolchain = {'name': 'intel', 'version': '2015a'}

source_urls = [
    'https://github.com/hpcugent/hanythingondemand/archive/'
]
sources = ['%s.tar.gz' % version]

python = 'Python'
pythonver = '2.7.10'
pythonshortver = '.'.join(pythonver.split('.')[:2])
versionsuffix = '-%s-%s' % (python, pythonver)

# a Python version with mpi4py and pbs_python (vsc.fancylogger) is required at runtime
dependencies = [
    (python, pythonver),
    ('pbs_python', '4.6.0', versionsuffix),
    ('vsc-mympirun', '3.4.2', '', True),
    ('vsc-base', '2.1.2', '', True),
]

options = {'modulename': 'hod', 'O': '1'}

moduleclass = 'tools'
```

**Comment by ehiggs** [comment]
@boegel's hod pr is [here](https://github.com/hpcugent/easybuild-easyconfigs/pull/1966/files).

**Comment by boegel** [comment]
I tried with `VersionDependentPythonPackage`, but also with `PythonPackage` and `Tarball`, couldn't get it to work with any of these...

In my git working directory it works, but only because I have a `hanythingondemand.egg-info/PKG-INFO` laying around, which 'fixes' relying on the `pkg_resources` stuff...

I don't think having a fallback is a big issue? The stuff that relies on `pkg_resources` should still be the first thing we try.

**Comment by boegel** [comment]
This is a non-issue if HOD is installed using setuptools/easy_install...

**Comment by boegel** [comment]
this is not an issue anymore if we install HOD 'correctly' (i.e., using setuptools), we use `hod dists` in the EB sanity check to make sure this works properly
