### ISSUE TITLE
'hod gencofig' is broken

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#83]
```
$ hod genconfig --workdir=$VSC_SCRATCH --hodconf=$EBROOTHANYTHING/etc/hod/IPython-notebook-3.2.1/hod.conf
2015-09-15 11:32:14,359 ERROR      not available in optimized mode.genconfig MainThread  Failed to setup hod tasks: ExtValues instance has no attribute 'modules'
2015-09-15 11:32:14,359 ERROR      not available in optimized mode.genconfig MainThread  hod-genconfig failed
Traceback (most recent call last):
  File "/apps/gent/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/hanythingondemand-3.0.0.dev0-py2.7.egg/hod/subcommands/genconfig.py", line 77, in run
    setup_tasks(svc)
  File "/apps/gent/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/hanythingondemand-3.0.0.dev0-py2.7.egg/hod/mpiservice.py", line 171, in setup_tasks
    svc.distribution(*master_template_kwargs)
  File "/apps/gent/SL6/sandybridge/software/hanythingondemand/3.0.0-beta-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/hanythingondemand-3.0.0.dev0-py2.7.egg/hod/hodproc.py", line 109, in distribution
    m_config = load_hod_config(config_path, self.options.workdir, self.options.modules)
AttributeError: ExtValues instance has no attribute 'modules'
```

**Comment by ehiggs** [comment]
Fix merged!
